# Generated by Django 4.1.3 on 2022-11-26 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('collection_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=1000)),
                ('movie_uuid', models.CharField(max_length=255, unique=True)),
                ('genre', models.CharField(max_length=255)),
                ('collection_uuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_collections.collections')),
            ],
        ),
    ]
