# Generated by Django 4.1.3 on 2022-11-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_collections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='collections',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='title',
        ),
    ]
