# Generated by Django 4.1.3 on 2022-11-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_collections', '0003_remove_movies_id_alter_movies_movie_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_uuid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
